apiVersion: v1
kind: ConfigMap
metadata:
  name: plate-reader-configmap-0.0.1
  namespace: default
data:
  driverProperties: |
    driverSku: Tecan SPark
    driverImage: edgenesis/plate-reader:v0.0.1
  instructions: |
    get_measurement:
    get_status:
    measure_plate:
    get_output:
# Telemetries are configurable health checks of the EdgeDevice
# Developer/user can configure certain instructions to be used as health check
# of the device. In this example, the device_health telemetry is mapped to
# "get_status" instruction, executed every 1000 ms
  telemetries: |
    device_health:
      properties:
        instruction: get_status
        initialDelayMs: 1000
        intervalMs: 1000
