apiVersion: v1
kind: ConfigMap
metadata:
  name: opcua-configmap-0.0.1
  namespace: default
data:
  driverProperties: |
    driverSku: Test OPC UA Server
    driverImage: 
  instructions: |
    get_value:
      instructionProperties:
        OPCUANodeID: "ns=2;i=2"
    get_time:
      instructionProperties:
        OPCUANodeID: "i=2258"
    get_server:
      instructionProperties:
        OPCUANodeID: "i=2261"
  telemetries: |
    telemetrySettings:
      updateIntervalMs: 1000
    telemetries:
      device_health:
        properties:
          instruction: get_server
          initialDelayMs: 1000
          intervalMs: 1000
   