apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: edgedevice-helloworld-deployment
  name: edgedevice-helloworld-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edgedevice-helloworld-deployment
  template:
    metadata:
      labels:
        app: edgedevice-helloworld-deployment
    spec:
      containers:
        - image: edgehub/deviceshifu-http-http:v0.0.1
          name: deviceshifu-http
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: edgedevice-config
              mountPath: "/etc/edgedevice/config"
              readOnly: true
          env:
            - name: EDGEDEVICE_NAME
              value: "edgedevice-helloworld"
            - name: EDGEDEVICE_NAMESPACE
              value: "devices"
      volumes:
        - name: edgedevice-config
          configMap:
            name: helloworld-configmap-0.0.1
      serviceAccountName: edgedevice-helloworld-sa

