apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: edgedevice-mockdevice-deployment
  name: edgedevice-mockdevice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edgedevice-mockdevice-deployment
  template:
    metadata:
      labels:
        app: edgedevice-mockdevice-deployment
    spec:
      containers:
      - image: edgehub/deviceshifu-http:v0.0.1
        name: deviceshifu-http
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: edgedevice-config
          mountPath: "/etc/edgedevice/config"
          readOnly: true
        env:
        - name: EDGEDEVICE_NAME
          value: "edgedevice-agv"
        - name: EDGEDEVICE_NAMESPACE
          value: "default"
      volumes:
      - name: edgedevice-config
        configMap:
          name: mockdevice-configmap-0.0.1
      serviceAccountName: edgedevice-readwrite-sa
