apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deviceshifu-thermometer-deployment
  name: deviceshifu-thermometer-deployment
  namespace: deviceshifu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deviceshifu-thermometer-deployment
  template:
    metadata:
      labels:
        app: deviceshifu-thermometer-deployment
    spec:
      containers:
      - image: edgehub/deviceshifu-http-http:nightly
        name: deviceshifu-http
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: deviceshifu-config
          mountPath: "/etc/edgedevice/config"
          readOnly: true
        env:
        - name: EDGEDEVICE_NAME
          value: "edgedevice-thermometer"
        - name: EDGEDEVICE_NAMESPACE
          value: "deviceshifu"
      - image: edgehub/gateway-lwm2m:nightly
        name: gateway-lwm2m
        volumeMounts:
          - name: deviceshifu-config
            mountPath: "/etc/edgedevice/config"
            readOnly: true
        env:
        - name: EDGEDEVICE_NAME
          value: "edgedevice-thermometer"
        - name: EDGEDEVICE_NAMESPACE
          value: "deviceshifu"
      volumes:
      - name: deviceshifu-config
        configMap:
          name: thermometer-configmap-0.0.1
      serviceAccountName: edgedevice-sa
