apiVersion: v1
kind: Namespace
metadata:
  name: devices
---
apiVersion: v1
kind: Namespace
metadata:
  name: deviceshifu
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: edgedevice-sa
  namespace: deviceshifu
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edgedevice-clusterrole
rules:
- apiGroups:
  - shifu.edgenesis.io
  resources:
  - edgedevices
  verbs: ["get", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: edgedevice-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edgedevice-clusterrole
subjects:
- kind: ServiceAccount
  name: edgedevice-sa
  namespace: deviceshifu
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edgedevice-telemetryservice-clusterrole
rules:
- apiGroups:
  - shifu.edgenesis.io
  resources:
  - telemetryservices
  verbs: ["get", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: edgedevice-telemetryservice-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edgedevice-telemetryservice-clusterrole
subjects:
- kind: ServiceAccount
  name: edgedevice-sa
  namespace: deviceshifu
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: shifu-crd-controller-manager
  namespace: shifu-crd-system