apiVersion: v1
kind: ConfigMap
metadata:
  name: deviceshifu-lwm2m
  namespace: deviceshifu
data:
#    device name and image address
  driverProperties: |
    driverSku: LwM2M Device
    driverImage: lwm2m-device:v0.0.1
#    available instructions
  instructions: |
    instructions:
      temperature:
        protocolPropertyList:
          ObjectId: /3303/0/5700
          EnableObserve: false
        gatewayPropertyList:
          ObjectId: /3303/0/5700
          DataType: float
      units:
        protocolPropertyList:
          ObjectId: /3303/0/5701
          EnableObserve: false
        gatewayPropertyList:
          ObjectId: /3303/0/5701
          DataType: string
      max:
        protocolPropertyList:
          ObjectId: /3303/0/5602
          EnableObserve: false
        gatewayPropertyList:
          ObjectId: /3303/0/5602
          DataType: float
      min:
        protocolPropertyList:
          ObjectId: /3303/0/5601
          EnableObserve: false
        gatewayPropertyList:
          ObjectId: /3303/0/5601
          DataType: float
      reset:
        protocolPropertyList:
          ObjectId: /3303/0/5605
          EnableObserve: false
        gatewayPropertyList:
          ObjectId: /3303/0/5605
